global:
  resolve_timeout: 5m

route:
  receiver: telegram
  group_by: ['...']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: '8007512489:AAGx4QRSFQ-KuWw1EClakpgtMbu4uVg-C8k'
        chat_id: 1382792490
        parse_mode: ''  # ÐžÑ‚ÐºÐ»ÑŽÑ‡Ð°ÐµÐ¼ Markdown
        message: |
          ðŸš¨ {{ .Status | toUpper }} ALERT: {{ .CommonLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Instance: {{ .CommonLabels.instance }}
          Job: {{ .CommonLabels.job }}
          Description: {{ .CommonAnnotations.description }}
